# Renders a "Sponsor" button on the repo and in issue/PR sidebars.
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
github: [Turbootzz]
